# Generated by Django 4.0.1 on 2022-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tbl_completed_tasks_tbl_new_task_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_completed_tasks',
        ),
        migrations.AddField(
            model_name='tbl_new_task',
            name='status',
            field=models.CharField(default='current', max_length=10),
        ),
    ]
